### ISSUE TITLE
Mastra.ai GitHub Issue タスク分解、推論

### ISSUE THREAD

**Issue by befi735** [befi735/TaskBoard#4]
Mastra.aiをGitHub Action定期スケジュールで実行し、Mastraタスク分解後にSub Issueとして書き込む実装コードを作成してください。

**Comment by befi735** [comment]
<think>
まず、Issueの内容を確認します。ユーザーはGitHub Actionを使用してMastra.aiを定期実行し、タスクを分解後にSub Issueとして作成する実装方法を求めています。

次に、解決策の概要をまとめます。GitHub Actionsでワークフローを作成し、Mastra.ai APIを呼び出してタスクを分解し、分解されたサブタスクをGitHub APIでIssueとして作成する必要があります。

推奨される解決策として、以下の手順を考えます：
1. GitHub Actionsのワークフローを定義し、定期実行を設定。
2. Mastra.aiのAPIキーをシークレットとして設定。
3. Mastra.ai APIを使用してタスクを分解。
4. 分解されたサブタスクをGitHub APIでIssueとして作成。

実装例として、ワークフロー定義ファイルとPythonスクリプトを提供します。ワークフローでは、Pythonジョブを使用してスクリプトを実行し、Mastra.ai APIとGitHub APIを呼び出します。

追加のアドバイスとして、APIエンドポイントの確認、シークレットの管理、デバッグの重要性を伝えます。

最後に、回答を構造化し、具体的なコード例を含めることで、ユーザーがすぐに実装できるようにします。
</think>

### 問題の概要
- GitHub Actionを使用してMasttra.aiを定期的に実行し、タスク分解後のSub IssueとしてIssueを作成する方法を求めています。

### 推奨される解決策
1. GitHub Actionsのワークフロー定義ファイルを作成します。
2. Masttra.aiのAPIを使用してタスク分解を実行します。
3. 分解されたタスクをSub IssueとしてGitHubのIssueに投稿します。

### 実装例

以下は実装例です：

#### GitHub Actionsのワークフロー定義ファイル (.github/workflows/masttra_workflow.yml)
```yaml
name: Masttra AI Task Decomposition

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時に実行

jobs:
  masttra-task-decomposition:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Masttra AI task decomposition
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MASTTRA_API_KEY: ${{ secrets.MASTTRA_API_KEY }}
        run: |
          python masttra_task_decomposition.py
```

#### Pythonスクリプト (masttra_task_decomposition.py)
```python
import os
import requests

def create_sub_issue(github_token, main_issue_number, title, body):
    headers = {
        "Authorization": f"Bearer {github_token}",
        "Content-Type": "application/json"
    }
    data = {
        "title": title,
        "body": body,
        "parent_issue_id": main_issue_number,
        "labels": ["sub-issue"]
    }
    response = requests.post(
        f"https://api.github.com/repos/{os.getenv('GITHUB_REPOSITORY')}/issues",
        headers=headers,
        json=data
    )
    return response.json()

def main():
    masttra_api_key = os.getenv("MASTTRA_API_KEY")
    github_token = os.getenv("GITHUB_TOKEN")
    main_issue_number = 123  # メインIssueの番号

    masttra_headers = {
        "Authorization": f"Bearer {masttra_api_key}"
    }
    response = requests.post(
        "https://api.masttra.ai/v1/task/decompose",
        headers=masttra_headers,
        json={
            "task": "your task description here"
        }
    )
    if response.status_code == 200:
        sub_tasks = response.json()["sub_tasks"]
        for i, sub_task in enumerate(sub_tasks):
            sub_issue_title = f"Sub Task {i+1}: {sub_task['title']}"
            sub_issue_body = f"Details: {sub_task['description']}"
            create_sub_issue(github_token, main_issue_number, sub_issue_title, sub_issue_body)
    else:
        print("Failed to decompose task")

if __name__ == "__main__":
    main()
```

### 追加のアドバイス
1. GitHub ActionsのシークレットにMasttra.ai APIキーとGitHubパーソナルアクセストークンを設定してください。
2. Masttra.ai APIのエンドポイントとレスポンス形式を事前に確認し、スクリプトを適宜調整してください。
3. issue作成に使用するGitHub APIの権限を正しく設定していることを確認してください。
4. デバッグ用に、ログ出力やエラーハンドリングを追加することをおすすめします。

以上の実装例を使用すると、GitHub Actions上でMasttra.aiを定期的に実行し、分解されたタスクをSub Issueとして自動的に作成することができます。
